# Generated by Django 5.1.2 on 2025-12-01 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='thumbsupdown',
            new_name='thumbsdown',
        ),
    ]
